# Creat a list

In [9]:
list1 = [1]
for i in range (1,18):
   list1 +=  [i+1]

print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [10]:
my_list = [ i for i in range(1, 19)]
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [11]:
m_list = list(range(1,19))
print(m_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


# Filename in function

In [7]:
def what(filename):
    c = print(filename + ".msh")
    notice = print("NOTICE:" + filename + " has been meshed successfully and saved as " + filename + ".msh")   
    return c 
    return notice
    

In [8]:
what("hao")

hao.msh
NOTICE:hao has been meshed successfully and saved as hao.msh


# File Location

In [13]:
import os
os.getcwd()

'/home/yanjun/Documents/FEniCSx/Tutorial'

below command can import function from other file directory

In [14]:
import sys
sys.path.append('/home/yanjun/Documents/FEniCSx/Tutorial/Mesh/')
from mesh_disc import mesh_brake_disc

In [16]:
import gmsh
gmsh.fltk.run()

Error   : Gmsh has not been initialized


# Function location


In [ ]:
import gmsh
outer_disc  = gmsh.model.occ.addCylinder(0,0,0,  0, 0, z1,  rd_o)

# np.full
list is [2,3,4,5]
array is [2 3 4 5]

In [39]:
import numpy as np

x = [1, 2, 3, 4, 5, 6, 7, 8]

x_array = np.array( [[1, 2, 3, 4], [ 5, 6, 7, 8]] )  # Convert x to a NumPy array

constant_value = 10
new_array = np.full(x_array.shape[1], constant_value)
print(new_array)

[10 10 10 10]


In [40]:
print(x)
print(x_array)

[1, 2, 3, 4, 5, 6, 7, 8]
[[1 2 3 4]
 [5 6 7 8]]
